import { trpc } from "@/lib/trpc";
import { AdministrationPanel, AgendaPanel } from "@/components/ClinicalAdministration";
import { CheckCircle2, FileText, ImagePlus, LockKeyhole, Plus, Search, ShieldCheck, Stethoscope, UserRound } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type QuoteLine =
  | { sourceType: "procedure"; sourceId: string; description: string; unitCents: number; quantity: number; discountPercent: number }
  | { sourceType: "manual"; sourceId?: string; description: string; unitCents: number; quantity: number; discountPercent: number };

const money = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(cents / 100);
const dateTime = (value: Date | string | null | undefined) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—";

function hexSha256(buffer: ArrayBuffer) {
  return crypto.subtle.digest("SHA-256", buffer).then((hash) => Array.from(new Uint8Array(hash)).map((byte) => byte.toString(16).padStart(2, "0")).join(""));
}

export default function ClinicalRecords() {
  const auth = trpc.auth.me.useQuery();
  const logout = trpc.auth.logout.useMutation({ onSuccess: () => auth.refetch() });
  const [accessEmail, setAccessEmail] = useState("luh.pessoa33@gmail.com");
  const [accessTokenHandled, setAccessTokenHandled] = useState(false);
  const requestAccessLink = trpc.administration.access.requestLink.useMutation({ onSuccess: () => toast.success("Se a conta estiver autorizada, o link de acesso foi enviado ao e-mail."), onError: (error) => toast.error(error.message) });
  const consumeAccessLink = trpc.administration.access.consumeLink.useMutation({ onSuccess: () => { window.history.replaceState({}, "", "/portal"); auth.refetch(); toast.success("Acesso confirmado"); }, onError: () => toast.error("O link de acesso é inválido, expirou ou já foi usado.") });
  const [query, setQuery] = useState("");
  const [selectedPatient, setSelectedPatient] = useState<{ id: string; fullName: string } | null>(null);
  const [patientForm, setPatientForm] = useState({ fullName: "", cpf: "", birthDate: "", contact: "" });
  const [assessment, setAssessment] = useState({ facial: "", capillary: "", body: "", summary: "", redFlags: false });
  const [evolution, setEvolution] = useState({ type: "Evolução", note: "" });
  const [consent, setConsent] = useState({ version: "imagem-clinica-v1", acceptedByName: "", id: "" });
  const [quoteLines, setQuoteLines] = useState<QuoteLine[]>([]);
  const [latestQuoteId, setLatestQuoteId] = useState<string | null>(null);
  const [issuedQuoteId, setIssuedQuoteId] = useState<string | null>(null);

  useEffect(() => {
    const token = new URLSearchParams(window.location.search).get("token");
    if (token && !accessTokenHandled) { setAccessTokenHandled(true); consumeAccessLink.mutate({ token }); }
  }, [accessTokenHandled, consumeAccessLink.mutate]);

  const patients = trpc.clinical.patients.search.useQuery({ term: query || "-" }, { enabled: query.trim().length >= 2 });
  const timeline = trpc.clinical.patients.timeline.useQuery({ patientId: selectedPatient?.id ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(selectedPatient) });
  const catalog = trpc.clinical.catalog.list.useQuery(undefined, { enabled: Boolean(auth.data) });
  const quoteDocument = trpc.clinical.quotes.clientDocument.useQuery({ quoteId: issuedQuoteId ?? "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(issuedQuoteId) });
  const createPatient = trpc.clinical.patients.create.useMutation({ onSuccess: (patient) => { setSelectedPatient(patient); setPatientForm({ fullName: "", cpf: "", birthDate: "", contact: "" }); toast.success("Paciente registrado com proteção de dados"); timeline.refetch(); } });
  const recordConsent = trpc.clinical.consents.recordImageClinical.useMutation({ onSuccess: (value) => { setConsent((current) => ({ ...current, id: value.id })); toast.success("Consentimento clínico de imagem registrado"); } });
  const saveAssessment = trpc.clinical.assessments.save.useMutation({ onSuccess: () => { toast.success("Avaliação registrada na linha de evolução"); timeline.refetch(); } });
  const saveEvolution = trpc.clinical.evolutions.create.useMutation({ onSuccess: () => { setEvolution({ type: "Evolução", note: "" }); toast.success("Evolução adicionada"); timeline.refetch(); } });
  const authorizePhoto = trpc.clinical.photos.createUpload.useMutation();
  const confirmPhoto = trpc.clinical.photos.confirmUpload.useMutation({ onSuccess: () => { toast.success("Foto clínica vinculada à evolução"); timeline.refetch(); } });
  const createQuote = trpc.clinical.quotes.create.useMutation({ onSuccess: (quote) => { setLatestQuoteId(quote.id); setIssuedQuoteId(null); toast.success("Orçamento criado. Revise e emita antes de imprimir."); } });
  const issueQuote = trpc.clinical.quotes.issue.useMutation({ onSuccess: () => { setIssuedQuoteId(latestQuoteId); toast.success("Orçamento emitido"); } });

  const quoteTotal = useMemo(() => quoteLines.reduce((sum, line) => sum + Math.round(line.unitCents * line.quantity * (100 - line.discountPercent) / 100), 0), [quoteLines]);

  if (auth.isLoading) return <div className="min-h-screen grid place-items-center text-sm text-slate-600">Abrindo ambiente protegido…</div>;
  if (!auth.data) return <LoginScreen email={accessEmail} setEmail={setAccessEmail} onSubmit={(event) => { event.preventDefault(); requestAccessLink.mutate({ email: accessEmail }); }} loading={requestAccessLink.isPending || consumeAccessLink.isPending} processingLink={consumeAccessLink.isPending || Boolean(new URLSearchParams(window.location.search).get("token"))} />;

  async function handlePhoto(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file || !selectedPatient) return;
    if (!consent.id) return toast.error("Registre primeiro o consentimento clínico de imagem.");
    try {
      const sha256 = await hexSha256(await file.arrayBuffer());
      const authorization = await authorizePhoto.mutateAsync({ patientId: selectedPatient.id, consentId: consent.id, contentType: file.type as "image/jpeg" | "image/png" | "image/webp", byteSize: file.size, sha256 });
      const upload = await fetch(authorization.uploadUrl, { method: "PUT", headers: authorization.requiredHeaders, body: file });
      if (!upload.ok) throw new Error("O armazenamento privado rejeitou o arquivo");
      await confirmPhoto.mutateAsync({ uploadIntentId: authorization.uploadIntentId, capturedAt: new Date() });
    } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível enviar a foto."); }
    finally { event.target.value = ""; }
  }

  function printQuote() {
    const data = quoteDocument.data;
    if (!data) return;
    const rows = data.items.map((item) => `<tr><td>${escapeHtml(item.description)}</td><td>${item.quantity}</td><td>${money(item.subtotalCents)}</td></tr>`).join("");
    const printWindow = window.open("", "_blank", "noopener,noreferrer,width=760,height=900");
    if (!printWindow) return toast.error("Permita pop-ups para imprimir o orçamento.");
    printWindow.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Orçamento LUmina</title><style>body{font-family:Arial,sans-serif;color:#183a36;margin:42px}h1{font-size:24px;margin:0}small{color:#58706c}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:12px 0;border-bottom:1px solid #d9e1de;text-align:left}.total{font-size:20px;font-weight:700;text-align:right;margin-top:20px}.note{margin-top:28px;white-space:pre-wrap;color:#45615c}</style></head><body><small>LUmina Skin Intelligence</small><h1>Orçamento</h1><p><strong>Cliente:</strong> ${escapeHtml(data.quote.clientNameSnapshot)}<br><strong>Validade:</strong> ${data.quote.validUntil ? escapeHtml(String(data.quote.validUntil)) : "Sob consulta"}</p><table><thead><tr><th>Item</th><th>Qtd.</th><th>Valor</th></tr></thead><tbody>${rows}</tbody></table><p class="total">Total: ${money(data.quote.totalCents)}</p>${data.quote.commercialMessage ? `<p class="note">${escapeHtml(data.quote.commercialMessage)}</p>` : ""}<small>Documento comercial. Não contém avaliação, evolução, fotografia, CPF ou dados clínicos.</small></body></html>`);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  }

  return (
    <main className="min-h-screen bg-[#f6f4ee] text-[#193b37]">
      <header className="sticky top-0 z-30 border-b border-[#dfe3dc] bg-[#fbfaf6]/92 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 lg:px-8">
          <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#183d37] text-[#e7bd7c]"><Stethoscope size={20} /></div><div><p className="font-semibold tracking-tight">LUmina · Prontuário Clínico</p><p className="text-xs text-[#6a7c77]">Ambiente privado · TiDB + R2</p></div></div>
          <div className="flex items-center gap-3"><a href="/" className="hidden rounded-xl border border-[#d6ddd8] px-3 py-2 text-sm hover:bg-white sm:block">Site público</a><span className="hidden text-right text-xs text-[#5f736d] sm:block">{auth.data.name}<br/><b>{auth.data.role === "super_admin" ? "SUPER ADM" : "PROFISSIONAL"}</b></span><button onClick={() => logout.mutate()} className="rounded-xl border border-[#d6ddd8] px-3 py-2 text-sm hover:bg-white">Sair</button></div>
        </div>
      </header>

      <AdministrationPanel role={auth.data.role} />
      <AgendaPanel role={auth.data.role} patient={selectedPatient} />
      <ConsentTemplateManager role={auth.data.role} patient={selectedPatient} />
      <div className="mx-auto grid max-w-7xl gap-5 px-5 py-6 lg:grid-cols-[300px_1fr] lg:px-8">
        <aside className="space-y-4"><section className="rounded-3xl bg-[#183d37] p-5 text-[#fbf8ee] shadow-xl shadow-[#183d37]/10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#e7bd7c]">Sessão protegida</p><h1 className="mt-3 text-xl font-semibold leading-snug">Registro de evolução com privacidade por padrão.</h1><ul className="mt-5 space-y-3 text-sm text-[#d9e5df]"><li className="flex gap-2"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[#e7bd7c]"/>CPF cifrado e pesquisável sem exibição.</li><li className="flex gap-2"><LockKeyhole size={17} className="mt-0.5 shrink-0 text-[#e7bd7c]"/>Fotos em bucket privado, URL temporária.</li><li className="flex gap-2"><FileText size={17} className="mt-0.5 shrink-0 text-[#e7bd7c]"/>Orçamento segregado do prontuário.</li></ul></section>
          <section className="rounded-3xl border border-[#dfe3dc] bg-white p-4"><label className="text-xs font-bold uppercase tracking-[.14em] text-[#59726b]">Localizar paciente</label><div className="mt-2 flex items-center gap-2 rounded-xl border border-[#d9e2dc] bg-[#fbfcfa] px-3"><Search size={16} className="text-[#789087]"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 w-full bg-transparent text-sm outline-none" placeholder="Nome (mín. 2 letras)" /></div><div className="mt-3 space-y-1">{patients.data?.map((patient) => <button key={patient.id} onClick={() => { setSelectedPatient(patient); setConsent((current) => ({ ...current, id: "" })); }} className={`w-full rounded-xl px-3 py-2 text-left text-sm transition ${selectedPatient?.id === patient.id ? "bg-[#eaf1ec] text-[#173e37]" : "hover:bg-[#f4f6f2]"}`}><b className="block truncate">{patient.fullName}</b><span className="text-xs text-[#71857e]">Atualizado {dateTime(patient.updatedAt)}</span></button>)}{query.trim().length >= 2 && !patients.isFetching && patients.data?.length === 0 && <p className="p-2 text-xs text-[#71857e]">Nenhum resultado.</p>}</div></section>
          <section className="rounded-3xl border border-[#dfe3dc] bg-white p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#59726b]">Novo registro</p><PatientForm form={patientForm} setForm={setPatientForm} onSubmit={(event) => { event.preventDefault(); createPatient.mutate({ ...patientForm, birthDate: patientForm.birthDate || null, contact: patientForm.contact || null }); }} busy={createPatient.isPending} /></section>
        </aside>

        <section className="min-w-0">{!selectedPatient ? <EmptyState /> : <div className="space-y-5"><div className="flex flex-col justify-between gap-3 rounded-3xl border border-[#dfe3dc] bg-white p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a7648]">Paciente selecionado</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{selectedPatient.fullName}</h2><p className="mt-1 text-sm text-[#647a73]">CPF permanece protegido; somente identificadores indispensáveis entram nesta tela.</p></div><div className="rounded-2xl bg-[#edf4ef] px-4 py-3 text-xs text-[#4c6b61]"><b>Fluxo:</b> consentimento → avaliação/evolução → foto → orçamento</div></div>
          <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-[#dfe3dc] bg-white p-5"><SectionTitle icon={<ShieldCheck size={18}/>} eyebrow="1 · Imagem" title="Consentimento antes da fotografia" /><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Versão do termo"><input value={consent.version} onChange={(event) => setConsent({ ...consent, version: event.target.value })} /></Field><Field label="Nome de quem consentiu"><input value={consent.acceptedByName} onChange={(event) => setConsent({ ...consent, acceptedByName: event.target.value })} placeholder="Nome completo" /></Field></div><button onClick={() => recordConsent.mutate({ patientId: selectedPatient.id, documentVersion: consent.version, acceptedByName: consent.acceptedByName, acceptedAt: new Date() })} disabled={!consent.acceptedByName || recordConsent.isPending} className="mt-4 rounded-xl bg-[#183d37] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{consent.id ? "Consentimento registrado" : "Registrar consentimento"}</button>{consent.id && <label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-[#bfd3c6] bg-[#f5faf6] px-4 py-3 text-sm text-[#31574b]"><ImagePlus size={18}/><span>Adicionar foto clínica privada</span><input className="hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={handlePhoto} /></label>}</section>
            <section className="rounded-3xl border border-[#dfe3dc] bg-white p-5"><SectionTitle icon={<UserRound size={18}/>} eyebrow="2 · Avaliação" title="Registro estruturado" /><div className="mt-4 grid gap-3"><Field label="Observação facial"><textarea value={assessment.facial} onChange={(event) => setAssessment({ ...assessment, facial: event.target.value })} placeholder="Observações profissionais, se aplicável" /></Field><Field label="Observação capilar"><textarea value={assessment.capillary} onChange={(event) => setAssessment({ ...assessment, capillary: event.target.value })} /></Field><Field label="Observação corporal"><textarea value={assessment.body} onChange={(event) => setAssessment({ ...assessment, body: event.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={assessment.redFlags} onChange={(event) => setAssessment({ ...assessment, redFlags: event.target.checked })} /> Sinal de alerta — requer encaminhamento antes de conclusão.</label></div><button onClick={() => saveAssessment.mutate({ patientId: selectedPatient.id, status: "completed", summaryText: assessment.summary || null, redFlags: assessment.redFlags ? ["Sinal de alerta marcado pela profissional"] : [], assessmentData: { facial: assessment.facial, capillary: assessment.capillary, body: assessment.body } })} disabled={saveAssessment.isPending} className="mt-4 rounded-xl border border-[#183d37] px-4 py-2.5 text-sm font-medium text-[#183d37]">Salvar avaliação</button></section></div>
          <div className="grid gap-5 xl:grid-cols-[1fr_1.1fr]"><section className="rounded-3xl border border-[#dfe3dc] bg-white p-5"><SectionTitle icon={<Plus size={18}/>} eyebrow="3 · Evolução" title="Linha do tempo clínica" /><Field label="Tipo"><input value={evolution.type} onChange={(event) => setEvolution({ ...evolution, type: event.target.value })} /></Field><Field label="Nota interna"><textarea value={evolution.note} onChange={(event) => setEvolution({ ...evolution, note: event.target.value })} placeholder="Apenas para o prontuário; nunca entra no orçamento." /></Field><button onClick={() => saveEvolution.mutate({ patientId: selectedPatient.id, evolutionType: evolution.type, privateNote: evolution.note || null, occurredAt: new Date(), assessmentId: null })} disabled={saveEvolution.isPending} className="mt-4 rounded-xl bg-[#183d37] px-4 py-2.5 text-sm font-medium text-white">Adicionar evolução</button><Timeline timeline={timeline.data} /></section>
            <section className="rounded-3xl border border-[#dfe3dc] bg-white p-5"><SectionTitle icon={<FileText size={18}/>} eyebrow="4 · Comercial" title="Orçamento entregue ao cliente" /><p className="mt-2 text-sm text-[#657c74]">Apenas descrição, quantidade, valores, desconto e total. Não envia observações, CPF, fotos ou evolução.</p><div className="mt-4 space-y-2">{catalog.data?.procedures.filter((procedure) => procedure.active).map((procedure) => <button key={procedure.id} onClick={() => setQuoteLines((lines) => [...lines, { sourceType: "procedure", sourceId: procedure.id, description: procedure.name, unitCents: procedure.defaultCents, quantity: 1, discountPercent: 0 }])} className="flex w-full items-center justify-between rounded-xl border border-[#dde5df] px-3 py-2 text-left text-sm hover:bg-[#f5f8f4]"><span>{procedure.name}</span><b>{money(procedure.defaultCents)}</b></button>)}</div><QuoteLines lines={quoteLines} setLines={setQuoteLines} /><div className="mt-4 flex items-center justify-between border-t border-[#e4e9e4] pt-4"><span className="font-semibold">Total</span><b className="text-xl">{money(quoteTotal)}</b></div><button onClick={() => createQuote.mutate({ patientId: selectedPatient.id, validUntil: null, commercialMessage: null, items: quoteLines })} disabled={!quoteLines.length || createQuote.isPending} className="mt-4 rounded-xl bg-[#b9894d] px-4 py-2.5 text-sm font-semibold text-[#1e352e] disabled:opacity-50">Gerar orçamento</button>{latestQuoteId && <div className="mt-3 flex flex-wrap gap-2">{!issuedQuoteId && <button onClick={() => issueQuote.mutate({ quoteId: latestQuoteId })} className="rounded-xl border border-[#b9894d] px-3 py-2 text-sm">Emitir</button>}{issuedQuoteId && <button onClick={printQuote} disabled={quoteDocument.isLoading || !quoteDocument.data} className="rounded-xl bg-[#183d37] px-3 py-2 text-sm text-white disabled:opacity-50">Imprimir / salvar PDF</button>}</div>}</section></div>
        </div>}</section>
      </div>
    </main>
  );
}

function ConsentTemplateManager({ role, patient }: { role: string; patient: { id: string; fullName: string } | null }) {
  const [open, setOpen] = useState(false);
  const [selectedId, setSelectedId] = useState("");
  const [acceptedByName, setAcceptedByName] = useState("");
  const [signedConsentId, setSignedConsentId] = useState<string | null>(null);
  const [draft, setDraft] = useState({ title: "", procedureId: "", version: "1.0", templateMarkdown: "" });
  const templates = trpc.clinical.consents.templates.list.useQuery({}, { enabled: open });
  const catalog = trpc.clinical.catalog.list.useQuery(undefined, { enabled: open && role === "super_admin" });
  const createDraft = trpc.clinical.consents.templates.createDraft.useMutation({ onSuccess: () => { toast.success("Modelo salvo como rascunho."); templates.refetch(); } });
  const approve = trpc.clinical.consents.templates.approve.useMutation({ onSuccess: () => { toast.success("Versão aprovada e bloqueada para edição."); templates.refetch(); } });
  const preview = trpc.clinical.consents.previewProcedure.useQuery({ patientId: patient?.id ?? "00000000-0000-0000-0000-000000000000", documentId: selectedId || "00000000-0000-0000-0000-000000000000" }, { enabled: Boolean(patient && selectedId) });
  const record = trpc.clinical.consents.recordProcedure.useMutation({ onSuccess: (result) => { setSignedConsentId(result.id); toast.success("Termo registrado com snapshot, data, hora e profissional."); setAcceptedByName(""); const popup = window.open("", "_blank", "noopener,noreferrer,width=760,height=900"); if (popup) { popup.document.write(`<!doctype html><meta charset=\"utf-8\"><title>Termo LUmina</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:42px;color:#173e37;white-space:pre-wrap;line-height:1.55}small{color:#657c74}</style><body>${escapeHtml(result.rendered)}<br><br><small>Registro gerado pela LUmina. A cópia do prontuário conserva o snapshot desta versão.</small></body>`); popup.document.close(); popup.print(); } } });
  const authorizeSignedPdf = trpc.clinical.documents.createSignedConsentUpload.useMutation();
  const confirmSignedPdf = trpc.clinical.documents.confirmSignedConsentUpload.useMutation({ onSuccess: () => toast.success("PDF assinado vinculado ao termo e protegido no prontuário.") });
  async function handleSignedPdf(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file || !patient || !signedConsentId) return;
    try {
      if (file.type !== "application/pdf") throw new Error("Selecione somente o PDF digitalizado do termo assinado.");
      const sha256 = await hexSha256(await file.arrayBuffer());
      const upload = await authorizeSignedPdf.mutateAsync({ patientId: patient.id, consentId: signedConsentId, contentType: "application/pdf", byteSize: file.size, sha256 });
      const response = await fetch(upload.uploadUrl, { method: "PUT", headers: upload.requiredHeaders, body: file });
      if (!response.ok) throw new Error("O armazenamento privado recusou o PDF");
      await confirmSignedPdf.mutateAsync({ patientId: patient.id, consentId: signedConsentId, objectKey: upload.objectKey, byteSize: file.size, sha256 });
    } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível vincular o PDF."); }
    finally { event.target.value = ""; }
  }
  if (!open) return <div className="mx-auto max-w-7xl px-5 pt-5 lg:px-8"><button onClick={() => setOpen(true)} className="rounded-xl border border-[#d6ddd8] bg-white px-4 py-2 text-sm text-[#31574b] hover:bg-[#f5f8f4]">Termos de consentimento por procedimento</button></div>;
  const selected = templates.data?.find((template) => template.id === selectedId);
  return <section className="mx-auto max-w-7xl px-5 pt-5 lg:px-8"><div className="rounded-3xl border border-[#dfe3dc] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a7648]">Termos versionados</p><h2 className="mt-1 text-xl font-semibold">Personalize por procedimento. Preserve a versão aceita.</h2><p className="mt-1 max-w-3xl text-sm text-[#657c74]">A titular escreve o conteúdo. O sistema só aplica os dados autorizados de paciente, procedimento, data, hora e profissional no momento do registro.</p></div><button onClick={() => setOpen(false)} className="text-sm text-[#657c74]">Fechar</button></div>
    {role === "super_admin" && <div className="mt-5 grid gap-3 rounded-2xl bg-[#f7faf7] p-4 lg:grid-cols-2"><Field label="Título do modelo"><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Definido pela titular" /></Field><Field label="Procedimento associado"><select value={draft.procedureId} onChange={(event) => setDraft({ ...draft, procedureId: event.target.value })}><option value="">Selecione</option>{catalog.data?.procedures.map((procedure) => <option key={procedure.id} value={procedure.id}>{procedure.name}</option>)}</select></Field><Field label="Versão"><input value={draft.version} onChange={(event) => setDraft({ ...draft, version: event.target.value })} placeholder="Ex.: 1.0" /></Field><Field label="Marcadores autorizados"><input readOnly value="{{PACIENTE_NOME}} · {{PROCEDIMENTO_NOME}} · {{DATA_REGISTRO}} · {{HORA_REGISTRO}} · {{PROFISSIONAL_NOME}}" /></Field><div className="lg:col-span-2"><Field label="Texto do termo — conteúdo definido pela titular"><textarea value={draft.templateMarkdown} onChange={(event) => setDraft({ ...draft, templateMarkdown: event.target.value })} placeholder="Insira somente a redação aprovada. O sistema não cria cláusulas automaticamente." /></Field></div><button onClick={() => createDraft.mutate({ title: draft.title, consentType: "procedure", procedureId: draft.procedureId, version: draft.version, templateMarkdown: draft.templateMarkdown })} disabled={!draft.title || !draft.procedureId || !draft.templateMarkdown || createDraft.isPending} className="w-fit rounded-xl bg-[#183d37] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">Salvar rascunho</button></div>}
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1fr]"><div><p className="text-sm font-semibold">Modelos disponíveis</p><div className="mt-2 space-y-2">{templates.data?.map((template) => <div key={template.id} className={`rounded-xl border p-3 ${selectedId === template.id ? "border-[#7ca78e] bg-[#f5faf6]" : "border-[#e0e7e1]"}`}><button onClick={() => { setSelectedId(template.id); setSignedConsentId(null); }} className="w-full text-left"><b className="block text-sm">{template.title}</b><span className="text-xs text-[#71857e]">v{template.version} · {template.status}</span></button>{role === "super_admin" && template.status === "draft" && <button onClick={() => approve.mutate({ documentId: template.id })} className="mt-2 rounded-lg border border-[#b9894d] px-2 py-1 text-xs">Aprovar versão</button>}</div>)}{templates.data?.length === 0 && <p className="text-sm text-[#71857e]">Nenhum modelo criado.</p>}</div></div><div className="rounded-2xl bg-[#fbfcfa] p-4"><p className="text-sm font-semibold">Registro para o prontuário</p>{!patient ? <p className="mt-2 text-sm text-[#71857e]">Selecione um paciente para gerar preview e registrar o termo.</p> : !selected || selected.status !== "approved" ? <p className="mt-2 text-sm text-[#71857e]">Selecione uma versão aprovada.</p> : <><p className="mt-2 text-sm text-[#657c74]">Paciente: <b>{patient.fullName}</b></p>{preview.data && <pre className="mt-3 max-h-48 overflow-auto rounded-xl border bg-white p-3 text-xs whitespace-pre-wrap">{preview.data.rendered}</pre>}<Field label="Nome de quem declara o aceite"><input value={acceptedByName} onChange={(event) => setAcceptedByName(event.target.value)} placeholder="Nome completo" /></Field><button onClick={() => record.mutate({ patientId: patient.id, documentId: selected.id, acceptedByName, signatureMethod: "assinatura_manual_digitalizada" })} disabled={!acceptedByName || record.isPending} className="mt-3 rounded-xl bg-[#183d37] px-4 py-2.5 text-sm text-white disabled:opacity-50">Registrar termo e imprimir</button>{signedConsentId && <label className="mt-3 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-[#bfd3c6] bg-[#f5faf6] px-4 py-3 text-sm text-[#31574b]"><FileText size={18}/><span>Vincular PDF digitalizado e assinado</span><input className="hidden" type="file" accept="application/pdf" onChange={handleSignedPdf}/></label>}<p className="mt-2 text-xs text-[#71857e]">O PDF retornado é privado, recebe verificação SHA-256 e fica vinculado à versão aceita. O sistema não afirma assinatura digital sem integração específica validada.</p></>}</div></div>
  </div></section>;
}

function LoginScreen({ email, setEmail, onSubmit, loading, processingLink }: { email: string; setEmail: (value: string) => void; onSubmit: (event: FormEvent) => void; loading: boolean; processingLink: boolean }) { return <main className="grid min-h-screen place-items-center bg-[#f6f4ee] px-5"><form onSubmit={onSubmit} className="w-full max-w-md rounded-[2rem] border border-[#dce4de] bg-white p-8 shadow-2xl shadow-[#183d37]/10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#183d37] text-[#e7bd7c]"><LockKeyhole size={21}/></div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-[#9a7648]">LUmina Skin Intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#183d37]">Acesso clínico protegido.</h1><p className="mt-3 text-sm leading-relaxed text-[#687d76]">O acesso é individual e usa um link único enviado para o e-mail autorizado. Fotos, CPF e evolução não são guardados no navegador.</p><div className="mt-6 space-y-4"><Field label="E-mail autorizado"><input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value )}/></Field></div><button disabled={loading || processingLink} className="mt-6 w-full rounded-xl bg-[#183d37] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{processingLink ? "Confirmando acesso…" : loading ? "Enviando link…" : "Enviar link de acesso"}</button><p className="mt-4 text-xs leading-relaxed text-[#71857e]">O link expira em 20 minutos e só pode ser usado uma vez. Se não houver conta autorizada, nenhuma informação sobre cadastros será revelada.</p></form></main>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-[#38574f]"><span>{label}</span><div className="mt-1 [&_input]:h-11 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-[#d9e2dc] [&_input]:bg-[#fbfcfa] [&_input]:px-3 [&_input]:outline-none [&_input:focus]:border-[#7ca78e] [&_textarea]:min-h-20 [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-[#d9e2dc] [&_textarea]:bg-[#fbfcfa] [&_textarea]:p-3 [&_textarea]:outline-none">{children}</div></label>; }
function SectionTitle({ icon, eyebrow, title }: { icon: React.ReactNode; eyebrow: string; title: string }) { return <div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#edf4ef] text-[#245448]">{icon}</span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#9a7648]">{eyebrow}</p><h3 className="font-semibold">{title}</h3></div></div>; }
function PatientForm({ form, setForm, onSubmit, busy }: { form: { fullName: string; cpf: string; birthDate: string; contact: string }; setForm: (value: { fullName: string; cpf: string; birthDate: string; contact: string }) => void; onSubmit: (event: FormEvent) => void; busy: boolean }) { return <form onSubmit={onSubmit} className="mt-3 space-y-3"><Field label="Nome completo"><input required value={form.fullName} onChange={(event) => setForm({ ...form, fullName: event.target.value })}/></Field><Field label="CPF"><input required inputMode="numeric" value={form.cpf} onChange={(event) => setForm({ ...form, cpf: event.target.value })}/></Field><Field label="Nascimento (opcional)"><input type="date" value={form.birthDate} onChange={(event) => setForm({ ...form, birthDate: event.target.value })}/></Field><Field label="Contato (opcional)"><input value={form.contact} onChange={(event) => setForm({ ...form, contact: event.target.value })}/></Field><button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#183d37] px-3 py-2.5 text-sm font-medium text-white disabled:opacity-50"><Plus size={16}/> Criar prontuário</button></form>; }
function Timeline({ timeline }: { timeline: { assessments: Array<{ id: string; createdAt: Date | string; status: string; redFlags: unknown }>; evolutions: Array<{ id: string; occurredAt: Date | string; evolutionType: string }>; photos: Array<{ id: string; createdAt: Date | string; originalFilename: string }> } | undefined }) { if (!timeline) return <p className="mt-5 text-sm text-[#71857e]">Carregando linha do tempo…</p>; const events = [...timeline.assessments.map((item) => ({ id: item.id, at: item.createdAt, title: `Avaliação · ${item.status}` })), ...timeline.evolutions.map((item) => ({ id: item.id, at: item.occurredAt, title: item.evolutionType })), ...timeline.photos.map((item) => ({ id: item.id, at: item.createdAt, title: `Foto clínica · ${item.originalFilename}` }))].sort((a, b) => new Date(b.at).getTime() - new Date(a.at).getTime()); return <div className="mt-5 space-y-2 border-t border-[#e4e9e4] pt-4">{events.length ? events.map((event) => <div key={event.id} className="flex items-center justify-between gap-4 rounded-xl bg-[#f7faf7] px-3 py-2 text-sm"><span className="truncate">{event.title}</span><span className="shrink-0 text-xs text-[#71857e]">{dateTime(event.at)}</span></div>) : <p className="text-sm text-[#71857e]">Ainda não há eventos registrados.</p>}</div>; }
function QuoteLines({ lines, setLines }: { lines: QuoteLine[]; setLines: (value: QuoteLine[]) => void }) { if (!lines.length) return <p className="mt-4 rounded-xl bg-[#f7faf7] p-3 text-sm text-[#71857e]">Selecione no catálogo os itens aprovados para o orçamento.</p>; return <div className="mt-4 space-y-2">{lines.map((line, index) => <div key={`${line.description}-${index}`} className="rounded-xl border border-[#e0e7e1] p-3"><div className="flex items-start justify-between gap-3"><b className="text-sm">{line.description}</b><button onClick={() => setLines(lines.filter((_, current) => current !== index))} className="text-xs text-[#a55a55]">Remover</button></div><div className="mt-2 grid grid-cols-3 gap-2 text-xs"><label>Qtd.<input type="number" min="1" value={line.quantity} onChange={(event) => setLines(lines.map((current, currentIndex) => currentIndex === index ? { ...current, quantity: Number(event.target.value) } : current))} className="mt-1 h-8 w-full rounded-lg border px-2"/></label>{line.sourceType === "manual" ? <label>Preço<input type="number" min="0" value={(line.unitCents / 100).toFixed(2)} onChange={(event) => setLines(lines.map((current, currentIndex) => currentIndex === index ? { ...current, unitCents: Math.round(Number(event.target.value) * 100) } : current))} className="mt-1 h-8 w-full rounded-lg border px-2"/></label> : <span className="pt-1.5 text-[#71857e]">Preço do catálogo<br/><b className="text-[#193b37]">{money(line.unitCents)}</b></span>}<label>Desc. %<input type="number" min="0" max="100" value={line.discountPercent} onChange={(event) => setLines(lines.map((current, currentIndex) => currentIndex === index ? { ...current, discountPercent: Number(event.target.value) } : current))} className="mt-1 h-8 w-full rounded-lg border px-2"/></label></div></div>)}</div>; }
function EmptyState() { return <div className="grid min-h-[65vh] place-items-center rounded-[2rem] border border-dashed border-[#cbd9cf] bg-white/60 p-10 text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#edf4ef] text-[#29594e]"><UserRound size={25}/></div><h2 className="mt-5 text-2xl font-semibold">Abra ou crie um prontuário.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-relaxed text-[#6c817a]">Use a pesquisa para localizar pelo nome. Para um novo registro, preencha nome completo e CPF no painel lateral; o CPF é cifrado no servidor antes de ser persistido.</p></div></div>; }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character] ?? character)); }
