export const ENV = {
  databaseUrl: process.env.DATABASE_URL ?? "",
  databaseSsl: process.env.DATABASE_SSL !== "false",
  databaseSslRejectUnauthorized: process.env.DATABASE_SSL_REJECT_UNAUTHORIZED !== "false",
  jwtSecret: process.env.JWT_SECRET ?? "",
  dataEncryptionKey: process.env.DATA_ENCRYPTION_KEY ?? "",
  bootstrapAdminEmail: process.env.BOOTSTRAP_ADMIN_EMAIL?.trim().toLowerCase() ?? "",
  bootstrapAdminName: process.env.BOOTSTRAP_ADMIN_NAME?.trim() ?? "Administradora LUmina",
  bootstrapAdminPasswordHash: process.env.BOOTSTRAP_ADMIN_PASSWORD_HASH ?? "",
  ownerEmail: process.env.OWNER_EMAIL?.trim().toLowerCase() ?? "luh.pessoa33@gmail.com",
  appBaseUrl: process.env.APP_BASE_URL?.replace(/\/$/, "") ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  authEmailFrom: process.env.AUTH_EMAIL_FROM ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  geminiModel: process.env.GEMINI_MODEL ?? "gemini-3.8-flash",
  isProduction: process.env.NODE_ENV === "production",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  s3Region: process.env.S3_REGION ?? "auto",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  uploadMaxBytes: Number(process.env.UPLOAD_MAX_BYTES ?? 10_000_000),
};
